# 📘 Day 14: Machine Learning Workflow — **Deep Theory + Hands-on (Tasks + Mini Project)**

---

## 🧭 What you’ll build today
- A **clear mental model** of the end-to-end ML lifecycle
- A **credit risk pipeline** (BFSI-aligned)
- Hands-on practice with **preprocessing, feature engineering, training, evaluation**
- Understanding of **deployment & monitoring (theory)**

---

## 📚 Table of Contents
1. Problem Definition  
2. Data Collection  
3. Data Preprocessing  
4. Feature Engineering  
5. Model Selection  
6. Training (Optimization intuition)  
7. Evaluation (metrics + pitfalls)  
8. Deployment (high-level)  
9. Monitoring & Drift  
10. 🧪 Mini Project (Credit Risk)  
11. 📝 Interview Questions

## 1️⃣ Problem Definition

### 🎯 What is it?
Translate a **business problem → ML problem**

### 🧠 Key decisions
- Regression vs Classification
- Target variable (y)
- Success metric

### 🏦 BFSI Example
> “Predict probability of loan default”

- Input (X): income, loan amount, employment years  
- Output (y): risk score / default probability  

---

### ❓ Task 1
Define:
1. Problem type  
2. Target variable  
3. Evaluation metric

## 2️⃣ Data Collection

### 📦 Sources
- Databases (SQL / Oracle)
- APIs
- Logs

### ⚠️ Reality
- Data is **messy, incomplete, biased**
- Most time spent here

---

### ❓ Task 2
List 3 possible data sources for:
- Fraud detection system

## 3️⃣ Data Preprocessing

### 🧹 Steps
- Handle missing values
- Normalize / scale
- Encode categorical variables

### ⚠️ Why important?
Models cannot learn from raw, inconsistent data

---

### 🔧 Example

In [2]:
import numpy as np
import pandas as pd

np.random.seed(42)

df = pd.DataFrame({
    "income": np.random.randint(20000, 100000, 10),
    "loan": np.random.randint(5000, 50000, 10)
})

# Introduce missing value
df.loc[3, "income"] = None

df.head

<bound method NDFrame.head of     income   loan
0  35795.0   6685
1  20860.0   5769
2  96820.0   7433
3      NaN  10311
4  26265.0  42819
5  57194.0  44188
6  64131.0  22568
7  80263.0  24769
8  36023.0  33693
9  61090.0  11396>

In [3]:
# TODO: Handle missing values
df_filled = df.fillna(df.mean())

df_filled

         income   loan
0  35795.000000   6685
1  20860.000000   5769
2  96820.000000   7433
3  53160.111111  10311
4  26265.000000  42819
5  57194.000000  44188
6  64131.000000  22568
7  80263.000000  24769
8  36023.000000  33693
9  61090.000000  11396

## 4️⃣ Feature Engineering (🔥 MOST IMPORTANT)

### 💡 Idea
Create better inputs → better model

### Example
loan_to_income = loan / income

---

### ❓ Task 3
Create a new feature:
- EMI ratio (loan / income)

In [4]:
# TODO: Create feature
df_filled["loan_to_income"] = df_filled["loan"] / df_filled["income"]

df_filled

         income   loan  loan_to_income
0  35795.000000   6685        0.186758
1  20860.000000   5769        0.276558
2  96820.000000   7433        0.076771
3  53160.111111  10311        0.193961
4  26265.000000  42819        1.630268
5  57194.000000  44188        0.772599
6  64131.000000  22568        0.351905
7  80263.000000  24769        0.308598
8  36023.000000  33693        0.935319
9  61090.000000  11396        0.186544

## 5️⃣ Model Selection

### Options
- Linear Regression (simple, interpretable)
- Logistic Regression (classification)
- Tree-based models (non-linear)

### ⚖️ Trade-off
- Simplicity vs Accuracy

---

### ❓ Task 4
When would you choose:
1. Linear Regression  
2. Decision Tree

## 6️⃣ Training (Where Gradient Descent fits)

Model learns patterns by minimizing loss.

---

### ❓ Task 5
What happens if:
- Learning rate is too high?
- Learning rate is too low?

## 7️⃣ Evaluation

### 📊 Metrics
- Regression → RMSE
- Classification → Accuracy, Precision, Recall

### ⚠️ Pitfalls
- Overfitting
- Underfitting

---

### ❓ Task 6
Why accuracy is NOT enough in fraud detection?

## 8️⃣ Deployment (Theory)

### Options
- REST API (FastAPI)
- Batch prediction
- Dashboard

---

### ❓ Task 7
Which deployment would you use for:
- Real-time fraud detection?

## 9️⃣ Monitoring & Drift

### 🔄 Why needed?
- Data changes over time
- Model performance drops

### Types
- Data drift
- Concept drift

---

### ❓ Task 8
What happens if model is not monitored?

## 🧪 Mini Project: Credit Risk Prediction (End-to-End)

---

### Step 1: Generate Data

In [5]:
import numpy as np

np.random.seed(42)

income = np.random.randint(20000, 100000, 100)
loan = np.random.randint(5000, 50000, 100)

risk = (loan / income) + np.random.normal(0, 0.05, 100)

### Step 2: Feature Engineering

In [6]:
X = np.column_stack((income, loan, loan/income))
y = risk

### Step 3: Train Model

In [7]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X, y)

LinearRegression()

### Step 4: Prediction

In [15]:
model.predict([[500000, 20000, 20000/50000]])

array([0.42975644])

## 📝 Interview Questions

1. Explain ML workflow end-to-end  
2. What is feature engineering?  
3. Difference between training and inference  
4. What is data drift?  
5. Why monitoring is critical?  

---

## 🔑 Final Takeaways

- ML = Pipeline, not just model  
- Feature Engineering = real power  
- Monitoring = real-world necessity